dist: trusty
sudo: required

language: node_js
node_js:
  - "6"

#cache:
#  directories:
#    - node_modules

services:
  - neo4j
  - redis-server

before_script:
  - npm install
  - cp ./config/travis/app3_tst2_s1_wb_key.pem ~
  - cp ./config/travis/app3_tst2_s1_wb_pub.pem ~
  - cp ./config/travis/pki1_tst2_ca_pub.pem ~
#  - sudo service neo4j stop
#  - sleep 20
#  - cp ./config/travis/data.tar ~
#  - sudo rm /var/lib/neo4j/certificates/neo4j.key
#  - sudo rm /var/lib/neo4j/certificates/neo4j.cert
#  - sudo cp ./config/travis/app3_tst2_s2_db_key.pem /var/lib/neo4j/certificates/neo4j.key
#  - sudo cp ./config/travis/app3_tst2_s2_db_pub.pem /var/lib/neo4j/certificates/neo4j.cert
#  - sudo rm -rd /var/lib/neo4j/data/databases
#  - (cd /var/lib/neo4j/data && sudo tar xvf ~/data.tar --strip 1)
#  - ls -al /var/lib/neo4j/data
#  - ls -al /var/lib/neo4j/data/databases
#  - cat /var/lib/neo4j/data/dbms/auth
#  - sudo service neo4j start
#  - sleep 30
#  - curl -vX POST http://neo4j:travis@localhost:7474/user/neo4j/password -d 'password=travis'
  - curl -vH "Content-Type:application/json" -X POST -d '{"password":"travis"}' -u neo4j:neo4j http://0.0.0.0:7474/user/neo4j/password

script:
  - curl http://neo4j:neo4j@localhost:7474/db/data/labels
  - swagger project start &
  - sleep 20
  - swagger project test

