dist: trusty
sudo: required

language: node_js
node_js:
  - "6"

services:
  - neo4j
  - redis-server

before_script:
  - npm install
  - cp ./config/travis/app3_tst2_s1_wb_key.pem ~
  - cp ./config/travis/app3_tst2_s1_wb_pub.pem ~
  - cp ./config/travis/pki1_tst2_ca_pub.pem ~
  - cp ./config/travis/data.tar ~
  - sudo service neo4j stop
  - sleep 20
  - sudo rm /usr/local/neo4j-"${NEO4J_VERSION}"/certificates/neo4j.key
  - sudo rm /usr/local/neo4j-"${NEO4J_VERSION}"/certificates/neo4j.cert
  - sudo cp ./config/travis/app3_tst2_s2_db_key.pem /usr/local/neo4j-"${NEO4J_VERSION}"/certificates/neo4j.key
  - sudo cp ./config/travis/app3_tst2_s2_db_pub.pem /usr/local/neo4j-"${NEO4J_VERSION}"/certificates/neo4j.cert
  - sudo ls -al /usr/local/neo4j-"${NEO4J_VERSION}"/data
  - sudo rm -rd /usr/local/neo4j-"${NEO4J_VERSION}"/data/databases
  - (cd /usr/local/neo4j-"${NEO4J_VERSION}"/data && sudo tar xvf ~/data.tar --strip 1)
  - sudo rm /usr/local/neo4j-"${NEO4J_VERSION}"/data/databases/graph.db/store_lock
  - sudo chown -R neo4j:neo4j /usr/local/neo4j-"${NEO4J_VERSION}"/data
  - sudo chown neo4j:adm /usr/local/neo4j-"${NEO4J_VERSION}"/data/databases
  - sudo chown neo4j:adm /usr/local/neo4j-"${NEO4J_VERSION}"/data/dbms
  - echo 'dbms.allow_format_migration=true' | sudo tee --append /etc/neo4j/neo4j.conf
  - sudo sed -i 's|dbms.security.auth_enabled=false|dbms.security.auth_enabled=true|g' /etc/neo4j/neo4j.conf
  - cat /etc/neo4j/neo4j.conf
  - sudo service neo4j start
  - sleep 30

script:
  - curl http://neo4j:"${DNB_APP_ENV_S2_DB_PASS}"@localhost:7474/db/data/labels
  - cat /var/log/neo4j/neo4j.log 
  - swagger project start &
  - sleep 20
  - swagger project test

