language: node_js
node_js:
  - "6"

before_script:
  - npm install
  - cp ./config/travis/app3_tst2_s1_wb_key.pem ~
  - cp ./config/travis/app3_tst2_s1_wb_pub.pem ~
  - cp ./config/travis/pki1_tst2_ca_pub.pem ~
  - cd /var/lib/neo4j-server/data/ && mkdir databases
  - cp ./config/travis/graph.db.tar.gz /var/lib/neo4j-server/data/databases
  - cd /var/lib/neo4j-server/data/databases && tar -zxf graph.db.tar.gz

script:
  - swagger project start &
  - sleep 20
  # - swagger project test

services:
  - neo4j

services:
  - redis-server
