# sudo: required
language: node_js
node_js:
  - "6"

before_script:
  - npm install
  - cp ./config/travis/app3_tst2_s1_wb_key.pem ~
  - cp ./config/travis/app3_tst2_s1_wb_pub.pem ~
  - cp ./config/travis/pki1_tst2_ca_pub.pem ~
  - cp ./config/travis/graph.db.tar.gz ~
  - sudo mkdir /var/lib/neo4j-server/data/databases
  - sudo tar -zxf ~/graph.db.tar.gz -C /var/lib/neo4j-server/data/databases
  - ls /var/lib/neo4j-server/data/databases/
  - curl -X POST https://neo4j:neo4j@localhost:7473/user/neo4j/password -d 'password=j4oen' --insecure

script:
  - swagger project start &
  - sleep 30
  - swagger project test

services:
  - neo4j

services:
  - redis-server
