dist: trusty
sudo: required

language: node_js
node_js:
  - "6"

services:
  - neo4j
  - redis-server

#before_install:
#  - cp ./config/travis/databases.tar ~
#  - sudo rm -rd /var/lib/neo4j/data/databases/graph.db
#  - cd /databases && sudo tar xvf ~/databases.tar --strip 1

before_script:
  - npm install
  - cp ./config/travis/app3_tst2_s1_wb_key.pem ~
  - cp ./config/travis/app3_tst2_s1_wb_pub.pem ~
  - cp ./config/travis/pki1_tst2_ca_pub.pem ~
  - cp ./config/travis/databases.tar ~
  - ls -al /var/lib/neo4j/import
  - sudo rm /var/lib/neo4j/certificates/neo4j.key
  - sudo rm /var/lib/neo4j/certificates/neo4j.cert
  - sudo cp ./config/travis/app3_tst2_s2_db_key.pem /var/lib/neo4j/certificates/neo4j.key
  - sudo cp ./config/travis/app3_tst2_s2_db_pub.pem /var/lib/neo4j/certificates/neo4j.cert
  - sudo rm -rd /var/lib/neo4j/data/databases/graph.db
  - (cd /var/lib/neo4j/data/databases && sudo tar xvf ~/databases.tar --strip 1)
  - ls /var/lib/neo4j/data/databases
  - curl -vX POST http://neo4j:neo4j@localhost:7474/user/neo4j/password -d 'password=travis'

script:
  - curl https://localhost:7473/db/data/labels --insecure
  - swagger project start &
  - sleep 20
  - swagger project test

